export const ADD_SUBSCRIBER_REQUEST = "ADD_SUBSCRIBER_REQUEST";
export const ADD_SUBSCRIBER_SUCCESS = "ADD_SUBSCRIBER_SUCCESS";
export const ADD_SUBSCRIBER_FAIL = "ADD_SUBSCRIBER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
